
############################################################
# Stop heating when open
############################################################
- alias: Heating - Stop when doors are open
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.openings
    to: 'on'
    from: 'off'
    for:
      minutes: 5
  condition:
    - condition: state
      entity_id: climate.netatmo_living_room
      attribute: preset_mode
      state: 'Schedule'
    # condition: not
    # conditions:
    #   - condition: state
    #     entity_id: climate.netatmo_living_room
    #     state: 'off'
  action:
    - service: automation.turn_on
      entity_id: automation.heating_restart_when_doors_are_closed
    - service: climate.set_preset_mode
      data:
        entity_id: climate.netatmo_living_room
        preset_mode: away

- alias: Heating - Restart when doors are closed
  trigger:
    - platform: state
      entity_id: group.openings
      to: 'off'
      from: 'on'
      for:
        minutes: 2
    - platform: event
      event_type: 2MN_AFTER_HASS_START
  # condition:
  #   - condition: state
  #     entity_id: climate.netatmo_living_room
  #     attribute: preset_mode
  #     state: 'away'
  #   - condition: state
  #     entity_id: group.openings
  #     state: 'off'
  action:
    - service: climate.set_preset_mode
      data:
        entity_id: climate.netatmo_living_room
        preset_mode: Schedule
    - service: automation.turn_off
      entity_id: automation.heating_restart_when_doors_are_closed

- alias: Heating - Stop monitoring when thermostat on away
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: climate.netatmo_living_room
      attribute: preset_mode
      to: 'away'
  action:
  - service: automation.turn_off
    entity_id: automation.heating_stop_when_doors_are_open

- alias: Heating - Restart monitoring when thermostat on Schedule
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: climate.netatmo_living_room
      attribute: preset_mode
      to: 'Schedule'
      for:
        minutes: 3
  action:
  - service: automation.turn_on
    entity_id: automation.heating_stop_when_doors_are_open



############################################################
# Boost when at home
############################################################
- alias: Heating - Boost when at home
  # initial_state: 'on'
  trigger:
    - platform: time
      at: '09:00:05'
    - platform: state
      entity_id: group.presence
      to: "home"
      for:
        minutes: 5
    - platform: state
      entity_id: group.openings
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: climate.netatmo_living_room
      attribute: preset_mode
      to: 'Schedule'
    - platform: numeric_state
      entity_id: climate.netatmo_living_room
      attribute: current_temperature
      below: 20.7
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: climate.netatmo_living_room
      attribute: temperature
      below: 21
      for:
        minutes: 5
  condition:
    - condition: time
      after: '9:00:00'
      before: '18:00:00'
    - condition: state
      entity_id: group.presence
      state: "home"
    - condition: state
      entity_id: group.openings
      state: 'off'
    - condition: state
      entity_id: climate.netatmo_living_room
      attribute: preset_mode
      state: 'Schedule'
    - condition: numeric_state
      entity_id: climate.netatmo_living_room
      attribute: current_temperature
      below: 20.7
    - condition: numeric_state
      entity_id: climate.netatmo_living_room
      attribute: temperature
      below: 21
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.netatmo_living_room
        temperature: 21
    - service: automation.turn_on
      entity_id: automation.heating_stop_boost
    - service: notify.ALL_MOBILES
      data:
        message: >-
          Brrr! It is only {{ state_attr('climate.netatmo_living_room', 'current_temperature') }} inside.
          Schedule mode will be reactivated at 6pm or when leaving home.
        title: Boost heating
    - service: tts.google_translate_say
      entity_id: media_player.living_room_speaker
      data:
        message: "Brrr, it's only {{ states.sensor.netatmo_l_olivaie_de_biot_living_room_temperature.state_with_unit }}, boost heating NOW !"


- alias: Heating - Stop boost
  # initial_state: 'off'
  trigger:
    - platform: time
      at: '18:00:05'
    - platform: state
      entity_id: group.presence
      to: "not_home"
      for:
        minutes: 5
    - platform: state
      entity_id: climate.netatmo_living_room
      attribute: preset_mode
      to: 'Schedule'
  action:
    - service: automation.turn_off
      entity_id: automation.heating_stop_boost
    - condition: not
      conditions:
        - condition: state
          entity_id: climate.netatmo_living_room
          state: 'off'
    - condition: state
      entity_id: climate.netatmo_living_room
      attribute: preset_mode
      state: 'manual'
    - service: notify.ALL_MOBILES
      data:
        message: >-
          It is
          {{ states.sensor.netatmo_l_olivaie_de_biot_living_room_temperature.state_with_unit }} inside,
          {{ states.sensor.netatmo_l_olivaie_de_biot_living_room_garden_temperature.state_with_unit }} outside.
        title: Thermostat back to schedule mode
    - service: climate.set_preset_mode
      data:
        entity_id: climate.netatmo_living_room
        preset_mode: Schedule

