################################################################
## Monitoring of critical devices
##
################################################################


################################################
## Customize
################################################
homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################
    package.node_anchors:
      customize: &customize
        package: 'monitor_criticals'

    ################################################
    ## Group
    ################################################
    group.critical_devices:
      <<: *customize

    ################################################
    ## Automation
    ################################################
    automation.alert_when_critical_device_not_available:
      <<: *customize

    ################################################
    ## Binary sensor
    ################################################
    binary_sensor.problem_critical_devices:
      <<: *customize
      # icon: mdi:bluetooth



################################################
## Group
################################################
group:
  critical_devices:
    name: Devices used for monitoring
    entities:
      - binary_sensor.motion_outside_porch
      - binary_sensor.motion_bar
      - binary_sensor.motion_living
      - binary_sensor.motion_garage
      - binary_sensor.motion_laundry
      - binary_sensor.motion_stairs
      - lock.z_wave_danalock_current_lock_mode
      - binary_sensor.opening_shutters_living
      - binary_sensor.opening_window_dining_left
      - binary_sensor.opening_window_dining_right
      - binary_sensor.opening_window_living
      - binary_sensor.opening_window_kitchen
      - binary_sensor.opening_catflap
      - binary_sensor.opening_door_entrance
      - binary_sensor.opening_door_garage
      - binary_sensor.opening_door_laundry
      - binary_sensor.smoke_sensor
      - camera.xiaofang
      - lock.front_door



################################################
## Binary sensor
################################################
binary_sensor:
  - platform: template
    sensors:
      problem_critical_devices:
        friendly_name: "Critical devices status"
        value_template: "{{ not(is_state('sensor.status_critical_devices', 'ok')) }}"
        # entity_id: sensor.status_critical_devices
        device_class: problem

sensor:
  - platform: template
    sensors:
      status_critical_devices:
        friendly_name: "Status of critical devices"
        value_template: >-
          {% macro check_critical_devices() %}
          {% for item in states.group.critical_devices.attributes.entity_id if (
            (states(item) == 'unknown') or
            is_state(item, 'unavailable') or
            is_state(item, 'dead')
          ) -%}
            {% if loop.index < 5 -%}
              {{ item if ((states(item) == 'unknown') or not state_attr(item, "friendly_name")) else state_attr(item, "friendly_name") }} is unavailable
            {% endif %}
          {% else %}
            {{ 'ok' }}
          {% endfor -%}
          {% endmacro %}
          {{ check_critical_devices() }}
        # entity_id:
        #   - binary_sensor.motion_outside_porch
        #   - binary_sensor.motion_bar
        #   - binary_sensor.motion_living
        #   - binary_sensor.motion_garage
        #   - binary_sensor.motion_laundry
        #   - binary_sensor.motion_stairs
        #   - zwave.polycontrol_danalock_v3_btze
        #   - lock.z_wave_danalock_current_lock_mode
        #   - binary_sensor.opening_shutters_living
        #   - binary_sensor.opening_window_dining_left
        #   - binary_sensor.opening_window_dining_right
        #   - binary_sensor.opening_window_living
        #   - binary_sensor.opening_window_kitchen
        #   - binary_sensor.opening_catflap
        #   - binary_sensor.opening_door_entrance
        #   - binary_sensor.opening_door_garage
        #   - binary_sensor.opening_door_laundry
        #   - binary_sensor.smoke_sensor
        #   - camera.xiaofang
        #   - lock.front_door
          




################################################
## Automation
################################################
automation:
  - alias: alert - critical device not available
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.problem_critical_devices
        to: 'on'
        from: 'off'
        for:
          minutes: 15
      - platform: time
        at: '09:00:00'
      - platform: time
        at: '21:00:00'
    condition:
      - condition: state
        entity_id: binary_sensor.problem_critical_devices
        state: 'on'
    action:
      - service: notify.notify
        data:
          title: "Critical devices monitoring"
          message: "{{ states('sensor.status_critical_devices') }}"
          data:
            apns_headers:
              'apns-collapse-id': 'critical_device_alert'
      - service: persistent_notification.create
        data:
          title: "Critical devices failures"
          message: "{{ states('sensor.status_critical_devices') }}"
          notification_id: critical_device_alert

############################################################
# Monitor some sensors every 15' and after boot
############################################################
  - alias: 'update sensor states regularly'
    initial_state: 'on'
    trigger:
      - platform: time_pattern
        minutes: '/30'
      - platform: event
        event_type: 2MN_AFTER_HASS_START
    action:
      # - service: homeassistant.update_entity
      #   entity_id: binary_sensor.problem_critical_devices
      - service: homeassistant.update_entity
        entity_id: sensor.status_critical_devices
        