################################################################
## Define all sensors and plants
##
################################################################

# 4BC9 Tomates 3 mur
# 6DFB Pepper 1
# 4CC3 Basil 4
# 6EC8 Arugula1
# 3CB6 Basil 3
# 4835 Basil 1

# C187 Avocado
# C5C6 Mimosa
# 720A verveine

# binary_sensor:
#   - platform: mqtt
#     name: "ESP 128:125:58:186:54:236"
#     state_topic: "ESP/128:125:58:186:54:236/state"
#     json_attributes_topic: "ESP/128:125:58:186:54:236/result"
#   - platform: mqtt
#     name: "ESP 128:125:58:184:153:204"
#     state_topic: "ESP/128:125:58:184:153:204/state"
#     json_attributes_topic: "ESP/128:125:58:184:153:204/result"


# plant:
#   - platform: plant_from_prefix
#     prefix: miflora_3cb6
#   - platform: plant_from_prefix
#     prefix: miflora_41fa



mqtt_plant:
  # - type: 'Parrot_POT'
  #   mac: 'A0:14:3D:CD:C2:84'


automation:
  - alias: 'Plant - Detect MQTT devices'
    trigger:
      platform: mqtt
      topic: plant_scanner/#
    action:
      - service: mqtt_plant.add_plant
        data:
          type: "{{ trigger.payload.split('/')[0] }}"
          mac: "{{ trigger.payload.split('/')[1] }}"
  - alias: 'Plant - monitor ESP'
    trigger:
      platform: mqtt
      topic: ESP/#
    action:
      - service: mqtt.publish
        data:
          topic: "homeassistant/binary_sensor/ESP_{{ trigger.topic.split('/')[1] |replace(':','_') }}/config"
          retain: false
          payload: >-
            {
              "name": "ESP {{ trigger.topic.split('/')[1] }} activity",
              "state_topic": "ESP/{{ trigger.topic.split('/')[1] }}/state",
              "device_class": "connectivity"
            }



