################################################################
## Vacuum and Laundry
################################################################

# vacuum:
#   - platform: xiaomi_miio
#     host: !secret rockrobo_vacuum_ip
#     token: !secret rockrobo_token
#     name: AspiBot


# sensor:
#   - platform: broadlink_power
#     host: !secret broadlink_plug_ip
#     mac: !secret broadlink_plug_mac
#     name: 'Laundry Machines'


# script:
#   'vacuum':
#     alias: Vacuum downstairs
#     sequence:
#       - service: vacuum.xiaomi_clean_zone
#         data:
#           entity_id: vacuum.aspibot
#           repeats: 0
#           zone:
#             - [20683,19635,25583,26085]
#             - [25514,22212,30164,26062]
#             - [28314,19518,29914,22318]
#             - [25558,19518,28308,20518]
#             # - [left: 20683, bottom: 19518, right: 30164, top: 26085]


#   'vacuum_return_to_base':
#     alias: Vacuum back 2 base
#     sequence:
#       - service: vacuum.return_to_base
#         entity_id: vacuum.aspibot

input_text:
  laundry_machine:
    name: active laundry machine


automation:
  ############################################################
  # Notify when laundry machines stop
  ############################################################
  - alias: Laundry - Monitor stop of laundry machines run
    # initial_state: 'off'
    trigger:
      platform: numeric_state
      entity_id: sensor.plug_sp3s_current_power
      below: '10'
      for:
        seconds: 130
    action:
      - service: tts.google_translate_say
        entity_id: media_player.living_room_speaker
        data:
          message: "{{ states('input_text.laundry_machine') }} is over."
      - service: notify.ALL_MOBILES
        data:
          title: Laundry completed
          message: "{{ states('input_text.laundry_machine') }} is over."
          data:
            push:
              thread-id: "laundry_monitor"
      - service: input_text.set_value
        data:
          entity_id: input_text.laundry_machine
          value: "Off"
      - service: automation.turn_on
        entity_id: automation.laundry_monitor_start_of_laundry_machines_run
      - service: automation.turn_off
        entity_id:
          - automation.laundry_monitor_stop_of_laundry_machines_run
          - automation.laundry_monitor_dryer

  - alias: Laundry - Monitor start of laundry machines run
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.plug_sp3s_current_power
      above: '1000'
      for:
        seconds: 130
    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.laundry_machine
          value: "Laundry"
      - service: automation.turn_on
        entity_id:
          - automation.laundry_monitor_stop_of_laundry_machines_run
          - automation.laundry_monitor_dryer
      - service: automation.turn_off
        entity_id: automation.laundry_monitor_start_of_laundry_machines_run

  - alias: Laundry - Monitor Dryer
    trigger:
      platform: numeric_state
      entity_id: sensor.plug_sp3s_current_power
      above: '2400'
      for:
        seconds: 190
    action:
      - service: input_text.set_value
        data:
          entity_id: input_text.laundry_machine
          value: "Dryer"


  ############################################################
  # Vacuum cleaner automation
  ############################################################
  - alias: Vacuum - Start when not home
    trigger:
    - platform: state
      entity_id: group.presence
      to: not_home
      for:
        minutes: 15
    - platform: time
      at: '11:00:05'
    condition:
    - condition: state
      state: not_home
      entity_id: group.presence
      for:
        minutes: 10
    - condition: time
      after: '11:00:00'
      before: '18:00:00'
      weekday:
      - mon
      - fri
    action:
    - service: vacuum.start
      entity_id: vacuum.aspibot
    - service: automation.turn_off
      entity_id: automation.vacuum_start_when_not_home

