################################################################
## Define all integrations
################################################################

# hacs:
#   token: !secret hacs_git_token

# xiaomi_aqara:
#   discovery_retry: 20
#   gateways:
#    - host:  !secret mi_gateway_ip
#      key: !secret mi_gateway_key
#      mac: !secret mi_gateway_mac

samsungtv_smart:
  - host: !secret samsung_tv_ip
    name: Samsung Q7
    api_key: !secret smartthings_token
    device_id: !secret smartthings_di
    mac: !secret samsungtv_mac
    # show_channel_number: true
    scan_app_http: false


netatmo:
  client_id: !secret netatmo_id
  client_secret: !secret netatmo_secret

# lock:
#   - platform: nuki
#     host: !secret nuki_bridge_ip
#     token: !secret nuki_token

ffmpeg:

camera:
  - platform: ffmpeg
    name: Xiaofang
    input: !secret xiaofang_camera_input
    extra_arguments: -an

  - platform: mjpeg
    name: espcam
    mjpeg_url: http://192.168.31.76/

  # - platform: generic
  #   name: Some Image
  #   still_image_url: rtsp://194.218.96.92:554
  #   stream_source: rtsp://194.218.96.92:554
  #   # verify_ssl: false

rpi_camera:
  image_width: 1296
  image_height: 972
  image_quality: 75
  timelapse: 2000
  file_path: /home/homeassistant/tmp/raspi.jpeg

# linky:
#   - username: !secret enedis_user
#     password: !secret enedis_password

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

# shelly:
#   discovery: True  #add all devices (default)
#   igmp_fix: True
#   mdns: True
#   scan_interval: 30
#   devices:  #configure devices
#     # - id: "008100"
#     #   name: "shutters living"
#     #   entity_id: shutters_living
#     - id: "7ae030"
#       name: "plug xiaomi gateway"
#       entity_id: plug_xiaomi_gateway
#     # - id: "e631d5-1"
#     #   name: "light@Pool"
#     #   light_switch: true  #add this switch as a light
#     #   entity_id: light_pool
#     # - id: "e631d5-2"
#     #   name: "lights@Trees"
#     #   light_switch: true  #add this switch as a light
#     #   entity_id: lights_trees
#     # - id: "24CE1A"
#     #   name: "light@Porch"
#     #   light_switch: true  #add this switch as a light
#     #   entity_id: light_porch

# rachio:
#   api_key: !secret rachio_api_key
#   hass_url_override: !secret rachio_hass_url_override
#   manual_run_mins: 3

# weather:
#   - platform: darksky
#     api_key: !secret dark_sky_key
#     mode: daily

meteo_france:
  - city: '06410'


device_tracker:
  - platform: xiaomi
    # track_new_devices: yes
    # interval_seconds: 30
    consider_home: 0:05
    host: !secret xiaomi_router_ip
    password: !secret xiaomi_router_pswd
    # new_device_defaults:
    #   track_new_devices: true


# switch:
#   - platform: xiaomi_miio
#     name: Mimie's Spring
#     host: !secret chuangmi_plug_ip
#     token: !secret chuangmi_miio_token


sensor:

  - platform: rpi_power
    text_state: true


  - platform: darksky
    api_key: !secret dark_sky_key
    forecast:
      - 0
      - 1
    hourly_forecast:
      - 0
    monitored_conditions:
      - precip_type
      - precip_intensity
      - precip_probability
      - wind_speed
      - wind_gust
      - uv_index
      - temperature
      - temperature_high
      - temperature_low
      - summary
      - alerts
    scan_interval:
      minutes: 5

