- id: '1621248504881'
  alias: Notify Lou
  description: ''
  trigger:
  - platform: state
    entity_id: person.lou
    to: home
    for: 00:05:00
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.living_room_speaker
      message: Coucou ma puce, tu penses a aller ramasser les Fraises STP
      language: fr
  mode: single
