- id: '1607955993058'
  alias: Motion-activated Light
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '120'
      motion_entity: binary_sensor.motion_bar
      light_target:
        entity_id: light.light_bar
- id: '1607956243965'
  alias: Motion-activated Light testbar
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '120'
      motion_entity: binary_sensor.motion_bar
      light_target:
        entity_id: light.light_bar
- id: '1607956628910'
  alias: Motion-activated Light mytest
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: 177
      motion_entity: binary_sensor.motion_bar
      light_target:
        entity_id: light.light_bar
- id: '1607979424385'
  alias: Motion-activated Light testme
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '120'
      motion_entity: binary_sensor.motion_bar
      light_target:
        entity_id: light.light_living
- id: '1607979577736'
  alias: Motion-activated Light testme
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '120'
      motion_entity: binary_sensor.motion_bar
      light_target:
        entity_id: light.light_living
