- platform: switch
  name: light@Garage
  entity_id: switch.wallswitch_light_garage
- platform: switch
  name: light@Laundry
  entity_id: switch.wallswitch_light_laundry
- platform: switch
  name: light@Kitchen
  entity_id: switch.wallswitch_light_kitchen
- platform: switch
  name: light@Living
  entity_id: switch.wallswitch_light_living
- platform: switch
  name: light@Bar
  entity_id: switch.wallswitch_light_bar
- platform: switch
  name: light@Stairs
  entity_id: switch.wallswitch_light_stairs
- platform: switch
  name: light@Lou_Ceiling
  entity_id: switch.wallswitch_light_lou_ceiling
- platform: switch
  name: light@Lou_Desk
  entity_id: switch.wallswitch_light_lou_wall


- platform: template
  lights:
    light_bedroom:
      friendly_name: "light@Bedroom"
      entity_id: light.bedroom_light
      value_template: "{{ is_state('light.bedroom_light', 'on') }}"
      level_template: "{{ state_attr('light.bedroom_light', 'brightness') | int }}"
      turn_on:
        service: light.turn_on
        entity_id: light.bedroom_light
        data_template:
          brightness: "{{ 255 if (now().hour >= 8) and (now().hour < 21) else 3 }}"
          kelvin: "{{ 4000 if (now().hour >= 8) and (now().hour < 21) else 2700 }}"
      turn_off:
        service: light.turn_off
        entity_id: light.bedroom_light
      set_level:
        service: light.turn_on
        entity_id: light.bedroom_light
        data_template:
          brightness: "{{ brightness }}"
          kelvin: "{{ (2700 + 1300 / 254 * (brightness - 1)) | int }}"

- platform: group
  name: lights_downstairs
  entities:
    - light.light_bar
    - light.light_kitchen
    - light.light_living


- platform: group
  name: lights_all
  entities:
    - light.light_bar
    - light.light_kitchen
    - light.light_living
    - light.gateway_light
    - light.light_garage
    - light.light_laundry
    - light.light_stairs
    - light.light_bedroom
    - light.light_lou_bed
    - light.light_lou_ceiling


- platform: mqtt
  name: "lights@Trees"
  state_topic: "shellies/shellyswitch25-E631D5/relay/1"
  command_topic: "shellies/shellyswitch25-E631D5/relay/1/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: false


- platform: mqtt
  name: "light@Pool"
  state_topic: "shellies/shellyswitch25-E631D5/relay/0"
  command_topic: "shellies/shellyswitch25-E631D5/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: false


- platform: mqtt
  name: "light@Porch"
  state_topic: "shellies/shelly1-24CE1A/relay/0"
  command_topic: "shellies/shelly1-24CE1A/relay/0/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
  optimistic: false
  retain: false
